# Authorization for Java application

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # namespace scoped | CluserRole is cluster scoped (could have used ClusterRole with a RoleBinding scoped within a namespace in order to reuse the role)

metadata:
  name: read-namespace-cluster-role
  # namespace: # only for kind: Role (ns scoped)

rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]