---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-operator
  namespace: flux
  
spec:
  template:
    spec:
      containers:
        - name: helm-operator
          
          args:
            # Enable only Helm version 3
            - --enabled-helm-versions=v3