apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system

spec:
  selector:
    istio: ingressgateway

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: java-demo-routes
  namespace: staging
spec:
  gateways:
    - public-gateway.istio-system.svc.cluster.local
  hosts:
    - java-demo-backend-service.staging.svc.cluster.local

  http:
    - name: "backend-route"
      route:
        - destination:
            host: java-demo-backend-service.staging.svc.cluster.local
