apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
nameSuffix: -staging

commonLabels:
    env: staging

bases:
  - ../bases/services/java-demo

resources:
  - services/java-demo/common/namespace.yaml
  - services/java-demo/common/rbac.yaml

patchesStrategicMerge:
  - services/java-demo/backend/deployment-patch.yaml
  - services/java-demo/database/deployment-patch.yaml