---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-backend-deployment
  namespace: java-demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-backend
      containers:
      - image: docker.io/jojoooo1/carros:rc-1.3.0-df61351ce6c316016d66ad92c2f6e96c75d925da
        name: java-demo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-database-deployment
  namespace: java-demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-database
      containers:
      - image: mysql:8.0.20
        name: java-demo-database
