---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-backend-deployment
  namespace: staging
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-backend
      containers:
      - image: docker.io/jojoooo1/carros:rc-1.3.0-2c4daf14aefde565a1596febfee706d857bfb042
        name: java-demo-backend
