---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-backend-deployment
  namespace: staging
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-backend
      containers:
      - image: docker.io/jojoooo1/carros:rc-1.1.0-28692bc0bf4a5ba90f9e0f2db199b783cafcdb5d
        name: java-demo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-database-deployment
  namespace: staging
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-database
      containers:
      - image: mysql:8.0.19
        name: java-demo-database
