apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv

spec:
  # Two way binding
  claimRef:
    name: mysql-pvc

  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc

spec:
  # Two way binding
  volumeName: mysql-pv