---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring-system
  annotations:
    fluxcd.io/automated: "false" # do not update automatically to prevent damaging the system

spec:
  chart:
    values:
      # https://github.com/helm/charts/tree/master/stable/prometheus-operator#configuration

      # CRD are created through kustomize (helm does not handle well CRD creation)
      prometheusOperator.createCustomResource: false

      # allows Prometheus operator to watch serviceMonitors outside of his namespace.
      prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false

      # Define persistent storage for Prometheus (PVC)
      prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.volumeName: prometheus-pv
      prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.accessModes: ["ReadWriteOnce"]
      prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 50mi

      # Define persistent storage for Grafana (PVC)
      grafana.adminPassword: password
      grafana.persistence.enabled: true
      grafana.persistence.storageClassName: grafana-pv
      grafana.persistence.accessModes:  ["ReadWriteOnce"]
      grafana.persistence.size: 50mi

      # Define persistent storage for Alertmanager (PVC)
      alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.accessModes: ["ReadWriteOnce"]
      alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.storageClassName: alertmanager-pv
      alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.resources.requests.storage: 50mi

      # Disable Etcd metrics
      kubeEtcd.enabled: false
      # Disable Controller metrics
      kubeControllerManager.enabled: false
      # Disable Scheduler metrics
      kubeScheduler.enabled: false



