---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  # namespace is set by kustomize
  
  annotations:
    fluxcd.io/automated: "false" # do not update automatically to prevent damaging the system

spec:
  values:
    # https://github.com/helm/charts/tree/master/stable/prometheus-operator#configuration

    kubeEtcd.enabled: false # Disable Etcd metrics
    kubeControllerManager.enabled: false # Disable Controller metrics
    kubeScheduler.enabled: false # Disable Scheduler metrics
    # CRD are created through kustomize (helm does not handle well CRD creation)
    prometheusOperator.createCustomResource: false
    # allows Prometheus operator to watch serviceMonitors outside of his namespace.
    prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false

    ## Deployed Prometheus instance Spec ##
    prometheus:
      prometheusSpec:
      # Bug (https://github.com/coreos/prometheus-operator/issues/2182 & https://github.com/helm/charts/issues/21501 [...])
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          fsGroup: 0
        retention: "15d"
        resources: {} # limit
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard # mandatory
              selector:
                matchLabels:
                  app: prometheus-pv
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Mi

    ## Deployed AlertManager instance Spec ##
    alertmanager:
      alertmanagerSpec:
        retention: "120h"
        resources: {} # limit
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: standard # mandatory
              selector:
                matchLabels:
                  app: alertmanager-pv
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Mi
                  
    ## Deployed Grafana instance Spec ##
    grafana:
      adminPassword: password
      persistence:
        enabled: true
        type: pvc
        existingClaim: grafana-pvc


