apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-namespace-rolebinding
  namespace: java-demo

# Target
subjects:
  - kind: ServiceAccount
    name: read-namespace
    namespace: java-demo

# Role
roleRef:
  kind: ClusterRole
  name: read-namespace-cluster-role
  apiGroup: rbac.authorization.k8s.io
