---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Backup
# kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml >master.key
# kubectl apply -f master.key
# kubectl delete pod -n kube-system -l name=sealed-secrets-controller

bases:
  - ../../../bases/sealed-secrets
