---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

commonLabels:
  k8s.managedkube.com/path: kubernetes-releases-base-gcp-cert-manager
  k8s.managedkube.com/app: cert-manager

resources:
  - crds
  - namespace
  - helm-release.yaml
