---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - namespace.yaml deleted to not caused errors because already defined in flux
  - crds.yaml
  - rbac.yaml
  - deployment.yaml
