---
apiVersion: v1
kind: Namespace

metadata:
  name: flux-system
  labels:
    istio-injection: enabled
  
  # annotations:
  #   linkerd.io/inject: disabled
  # labels:
  #   istio-injection: disabled
  #   appmesh.k8s.aws/sidecarInjectorWebhook: disabled