---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-backend-deployment
  namespace: minikube
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-backend
      containers:
      - image: docker.io/jojoooo1/carros:rc-1.3.4-b68b9d8ee1d13451f8e9033326d022cbf72c7b63
        name: java-demo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-database-deployment
  namespace: minikube
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: java-demo-database
      containers:
      - image: mysql:8.0.20
        name: java-demo-database
