
---
# Used by spring boot app
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-namespace-rolebinding
  # namespace is set by kustomize

# Target
subjects:
  - kind: ServiceAccount
    name: read-namespace
    # namespace is set by kustomize

# Role
roleRef:
  kind: ClusterRole
  name: read-namespace-cluster-role
  apiGroup: rbac.authorization.k8s.io
