apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace you be placed at top parent

bases:
  - ../../../bases/flagger/flagger
  - ../../../bases/flagger/prometheus
patchesStrategicMerge:
  - patch.yaml

resources:
  - namespace.yaml
