---
apiVersion: v1
kind: ConfigMap

metadata:
  name: carros
  # namespace set in corresponding env folder via kustomize

data:
  application.yml: |-
    # MySQL
    spring:

      datasource:
        url: jdbc:mysql://java-demo-database-service:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: jonathan
        password: password
