apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# BE BECAREFULL IF CREATED CAN NOT CHANGE IT
# => From apps/v1 on, a Deployment’s label selector is immutable after it gets created. (can fucked up your deployment)
# commonLabels => Set labels on all Resources and Selectors.
# selector:
#     matchLabels:
#       app: foo # Selector was changed
#       environment: test # Selector was added

bases:
  - ../../../bases/services/java-demo
patchesStrategicMerge:
  - java-demo/backend/deployment-annotations.yaml
  - java-demo/database/deployment-annotations.yaml

resources:
  - common/namespace.yaml
  - common/rbac.yaml
  - gateway.yaml

# var: can be referenced in YAML as $(MY_VAR_NAME)
# vars:
#   - name: SOME_SECRET_NAME
#     objref:
#       kind: Secret
#       name: my-secret
#       apiVersion: v1
#   - name: MY_SERVICE_NAME
#     objref:
#       kind: Service
#       name: my-service
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.name