apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../bases/logging

patchesJson6902:
  # Replace helm operator arguments
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: elasticsearch-logging
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1


