apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv

spec:
  # storageClassName: standard
  
  # Specifying a claimRef in a PV does not prevent the specified PVC from being bound to a different PV
  claimRef:
    name: grafana-pvc
    # needed => kustomize does not add it
    namespace: monitoring-system
    
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-system
  
spec:
  # Specifying a volumeName in your PVC does not prevent a different PVC from binding to the specified PV before 
  volumeName: grafana-pv
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce

# INFO: To ensure claim gets bound to the volume must ensure that both volumeName and claimRef are specified. 