# INFO: To ensure two wy binding must ensure that both 1. *volumeName* and 2. *claimRef* are specified.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv

spec:
  claimRef:
    name: grafana-pvc
    namespace: monitoring-system # needed => kustomize.namespace does not add it
    
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-system
  
spec:
  volumeName: grafana-pv
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce