apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 50Mi