---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  # https://hub.helm.sh/charts/bitnami/external-dns
  releaseName: external-dns
  chart:
    name: external-dns
    repository: https://kubernetes-charts.storage.googleapis.com/ # ExternalDNS version: 0.7.1
    version: 3.0.2
  values:
    resources:
      limits:
        memory: 50Mi
      requests:
        memory: 50Mi
        cpu: 10m

    # DNS Creation
    # upsert-only: would prevent ExternalDNS from deleting any records, omit to enable full synchronization
    # sync: would allow for deletes
    policy: sync

    # These help tell which records are owned by external-dns.
    registry: "txt"
    txtOwnerId: "k8s"

    logLevel: debug

    rbac:
      create: true
