---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

commonLabels:
  k8s.managedkube.com/path: kubernetes-releases-base-gcp-external-dns
  k8s.managedkube.com/app: external-dns

resources:
  - helm-release.yaml
