apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: staging
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: service-prometheus
  namespace: staging
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: java-demo

  logLevel: info
  retention: 1d
