apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: flagger-grafana
  namespace: istio-system

spec:
  releaseName: flagger-grafana
  chart:
    repository: https://flagger.app
    name: grafana
    version: 1.4.0 # mandatory
  values:
    url: http://prometheus.istio-system:9090
    user: admin
    password: password