apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../bases/services/java-demo

resources:
  - services/common/namespace.yaml
  - services/common/rbac.yaml

patchesStrategicMerge:
  - services/java-demo/backend/deployment-annotations.yaml
  - services/java-demo/database/deployment-annotations.yaml