apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flagger-system
commonLabels:
  app: flagger
resources:
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
images:
  - name: weaveworks/flagger
    newTag: 1.0.0-rc.4
