# INFO: To ensure two wy binding must ensure that both 1. *volumeName* and 2. *claimRef* are specified.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  labels:
    app: alertmanager-pv

spec:
  # claimRef:
  #   name: alertmanager-pvc
  # # bug: kustomize does not template claimRef
  #   namespace: monitoring-system
  
  storageClassName: standard # mandatory
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"