apiVersion: apps/v1
kind: Deployment

metadata:
  name: flux

spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux-system
            - --memcached-service=
            - --git-poll-interval=5m
            - --sync-interval=5m
            - --ssh-keygen-dir=/var/fluxd/keygen

            - --git-branch=master
            - --git-path=staging

            - --git-url=git@github.com:jojoooo1/java-demo-flux
            - --git-email=chevalier.jonathan@live.fr
            
            # Garbage collection enable
            - -sync-garbage-collection