---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-database-deployment
  labels:
    app: java-demo
    role: database

spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: java-demo
      role: database

  template:
    metadata:
      labels:
        app: java-demo
        role: database

    spec:
      serviceAccountName: default # d. if you wanna set specific RBAC to the pod
      containers:
        - name: java-demo-database
          image: mysql
          imagePullPolicy: IfNotPresent # d. Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "database"
            - name: MYSQL_USER
              value: "jonathan"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306

          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
