apiVersion: apps/v1
kind: Deployment

metadata:
  name: flux

spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux-system
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen

            - --git-path=staging/minikube
            - --git-branch=master
            - --git-url=git@github.com:jojoooo1/java-demo-flux

            - --git-label=flux-sync
            - --git-user=Flux
            - --git-email=chevalier.jonathan@live.fr

            - --git-poll-interval=5m # d.

            # Delete resources that were created by fluxd, but are no longer in the git repo
            - --sync-garbage-collection=true
            - --sync-interval=5m # d.