---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default
  # namespace is set by kustomize
  
spec:
  profile: default
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
