# Sets in this folder in order to be scoped by kustomize namespace
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: java-demo-backend-virtual-service
  # namespace is set by kustomize
  
spec:
  gateways:
    - public-gateway.default.svc.cluster.local
  hosts:
    - "*"
    # - java-demo-backend-service.default.svc.cluster.local

  http:
      # if multiple services use match
    - name: "java-demo-backend"
      route:
        - destination:
            # WARNING: set to corresponding namespace
            host: java-demo-backend-service.minikube.svc.cluster.local
            port:
              number: 8080
      